apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: production
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: NodePort
  selector:
    app: redis
